CREATE DATABASE PROVA

USE PROVA

CREATE TABLE TBL_INSTRUMENTOS
(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 INSTRUMENTO VARCHAR(100) NOT NULL,
 TIPO 		 VARCHAR(30)      NOT NULL, 
 MARCA       VARCHAR(100) NOT NULL,
 PRECO		 VARCHAR(100) NOT NULL);
 
 

 

 
select * from TBL_INSTRUMENTOS